### PR TITLE
CTDA-1281 Add metrics collection to controllers and connectors

### PR DESCRIPTION
**Pull request by DavidGregory084**
This PR adds metrics collection to all of the controller endpoints and connector calls in this repository. I'll send a follow-up PR to add these new metrics to the Grafana dashboard.
Interested in feedback about the metric names from those with more experience of the domain. :)

### CODE REVIEW

**Comment by ParoolPatel** [comment]
Got this to my personal gmail acct!
Is this really for me?

**Comment by DavidGregory084** [comment]
Don't worry @ParoolPatel I thought code review auto assignment was enabled but it was not 😆 I will direct this to someone more relevant

**Comment by ParoolPatel** [comment]
Lol

**Comment by behrsina** [comment]
Could you remove me as well as I don't review code?

**Review by crystalmark — APPROVED** [review]

**Comment by DavidGregory084** [comment]
@crystalmark could you have another quick look? I have added histograms to document the number of arrivals, departures and corresponding messages that are returned by each endpoint. I also have refactored HasMetrics a little bit as some of the code was copied from another project (LocalMetrics) etc. and was not really needed.

**Pull request merged**
