### PR TITLE
CTDA-815: Add Audit Event for MesSenMES3 added

### PR DESCRIPTION
**Pull request by marcinkrykowski**

### CODE REVIEW

**Review by RobertLaverick — APPROVED** [review]
Wait for @crystalmark to approve as well, but I'm ok with this.

Are you working on the assumption that the JSON conversion will be happening in another PR? (i.e. by @GeorgeColdham ?)

**Comment by GeorgeColdham** [comment]
> Wait for @crystalmark to approve as well, but I'm ok with this.
> 
> Are you working on the assumption that the JSON conversion will be happening in another PR? (i.e. by @GeorgeColdham ?)

Yeah, I made the assumption the actual conversion would be done as part of the audit tickets.

**Comment by jhkldev** [comment]
I was told there would need to be a 3 amigos for this. I've done the same changes locally.

**Comment by marcinkrykowski** [comment]
@GeorgeColdham Should I add anything or can I just wait for your PR to be merged?

**Pull request merged**
